apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
    - name: hello-cntr
      image: nigelpoulton/k8sbook:1.0
      ports:
        - containerPort: 8080
